In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets.samples_generator import make_blobs
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report, f1_score, precision_recall_curve
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import roc_curve, roc_auc_score,auc
from sklearn.feature_selection import VarianceThreshold
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectFromModel
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler 



In [2]:
fullFileName='twitter.csv'
data=pd.read_csv(fullFileName, sep=' ')

data_=data.replace(['1:','2:','3:','4:','5:','6:','7:','8:','9:','10:','11:','12:','13:','14:','15:','16:','17:','18:','19:',
                   '20:','21:','22:','23:','24:','25:','25:','27:','28:','29:','30:','31:','32:','33:','34:','35:','36:','37:','38:','39:','40:','50:','60:'],'',regex=True).astype(float) 

data_.columns = ['user_class','Number of followers per followees','Fraction of tweets replied','Fraction of tweets with spam words',
'Fraction of tweets with URLs','Existence of spam words in the screen name','Number of hashtags_mean',
'Number of hashtags_median','Number of hashtags_min','Number of hashtage_max',
'Number of URLs _mean','Number of URLs _median','Number of URLs _min','Number of URLs _max',
'Number of characters per tweet_mean','Number of characters per tweet_median','Number of characters per tweet_min','Number of characters per tweet_max',
'Number of hashtags per tweet_mean','Number of hashtags per tweet_median','Number of hashtags per tweet_min','Number of hashtags per tweet_max',
'Number of mentions per tweet_mean','Number of mentions per tweet_median','Number of mentions per tweet_min','Number of mentions per tweet_max',
'Number of numeric characters per tweet_mean','Number of numeric characters per tweet_median','Number of numeric characters per tweet_min','Number of numeric characters per tweet_max',
'Number of URLs on each tweet_mean','Number of URLs on each tweet_median','Number of URLs on each tweet_min','Number of URLs on each tweet_max',
'Number of words per tweet_mean','Number of words per tweet_median','Number of words per tweet_min','Number of words per tweet_max',
'number of times the tweet has been retweeted_mean','number of times the tweet has been retweeted_median','number of times the tweet has been retweeted_min','number of times the tweet has been retweeted_max',
'Number of followees','Number of followers','Number of tweets','Nnumber of followees of a user’s followers','Number of times mentioned',
'Number of times the user was replied','Number of times the user replied','Number of tweets of a user’s followees','Time between posts_mean','Time between posts_median',
'Time between posts_min','Time between posts_max','Number of posted tweets per day_mean','Number of posted tweets per day_median','Number of posted tweets per day_min',
'Number of posted tweets per day_max','Number of posted tweets per day_mean','Number of posted tweets per day_median','Number of posted tweets per day_min','Number of posted tweets per day_max','Age of the user account']




In [3]:
#first we count the number of missing values in each row in pandas dataframe
data_.isnull().sum(axis=0)
print("Dataset Lenght:: ",len(data_))
print("Dataset shape:: ", data_.shape)

Dataset Lenght::  1064
Dataset shape::  (1064, 63)


In [4]:
print("Dataset:: ")
data_.head()
data_.info()
data_.describe()

Dataset:: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1064 entries, 0 to 1063
Data columns (total 63 columns):
user_class                                             1064 non-null float64
Number of followers per followees                      1064 non-null float64
Fraction of tweets replied                             1064 non-null float64
Fraction of tweets with spam words                     1064 non-null float64
Fraction of tweets with URLs                           1064 non-null float64
Existence of spam words in the screen name             1064 non-null float64
Number of hashtags_mean                                1064 non-null float64
Number of hashtags_median                              1064 non-null float64
Number of hashtags_min                                 1064 non-null float64
Number of hashtage_max                                 1064 non-null float64
Number of URLs _mean                                   1064 non-null float64
Number of URLs _median             

user_class  Number of followers per followees  \
count  1064.000000                        1064.000000   
mean      1.333647                           1.275642   
std       0.471737                           6.157445   
min       1.000000                           0.000000   
25%       1.000000                           0.313268   
50%       1.000000                           0.739994   
75%       2.000000                           1.100000   
max       2.000000                         166.020833   

       Fraction of tweets replied  Fraction of tweets with spam words  \
count                 1064.000000                         1064.000000   
mean                     0.229468                            0.134967   
std                      0.212837                            0.339470   
min                      0.000000                            0.000000   
25%                      0.006253                            0.000000   
50%                      0.191407                            0.000000   
75%                      0.384394                            0.002291   
max                      1.000000                            1.000000   

       Fraction of tweets with URLs  \
count                   1064.000000   
mean                       0.413622   
std                        0.357267   
min                        0.005457   
25%                        0.112835   
50%                        0.268197   
75%                        0.738952   
max                        1.000000   

       Existence of spam words in the screen name  Number of hashtags_mean  \
count                                 1064.000000              1064.000000   
mean                                     0.003759                 0.030917   
std                                      0.061227                 0.046346   
min                                      0.000000                 0.000000   
25%                                      0.000000                 0.003700   
50%                                      0.000000                 0.010700   
75%                                      0.000000                 0.039750   
max                                      1.000000                 0.388500   

       Number of hashtags_median  Number of hashtags_min  \
count                1064.000000             1064.000000   
mean                    0.035823                0.010807   
std                     0.093575                0.041792   
min                     0.000000                0.000000   
25%                     0.000000                0.000000   
50%                     0.000000                0.000000   
75%                     0.000000                0.000000   
max                     1.000000                0.375000   

       Number of hashtage_max  ...  Time between posts_max  \
count             1064.000000  ...            1.064000e+03   
mean                 0.403525  ...            5.070877e+07   
std                  0.309248  ...            1.131179e+08   
min                  0.000000  ...            5.000000e+01   
25%                  0.166700  ...            5.281914e+06   
50%                  0.272700  ...            5.823160e+06   
75%                  0.500000  ...            5.256034e+07   
max                  1.000000  ...            5.606784e+08   

       Number of posted tweets per day_mean  \
count                           1064.000000   
mean                             199.379297   
std                              477.707017   
min                               50.012900   
25%                               51.000000   
50%                               53.093900   
75%                               59.053850   
max                             5373.000000   

       Number of posted tweets per day_median  \
count                             1064.000000   
mean                               201.963346   
std                                545.202549   
min                                 50.000000   
25%         

In [5]:
array=data_.values
X1 = array[:,1: ] 
Y = array[:,0]
 
""" MIN MAX SCALER """
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
# Scaled feature 
X2 = min_max_scaler.fit_transform(X1) 
  
""" Standardisation """ 
Standardisation = preprocessing.StandardScaler() 
# Scaled feature 
X = Standardisation.fit_transform(X2) 

#Spliting Dataset into Test and Train
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=0.2, random_state=0)




In [6]:
#calculate TP, TN,FN,FP
def compute_tp_tn_fn_fp(actual_y, predicted_y):
    #we define spam class(2) as positive rate, and not spam class(1) as negative rate
    #True positive _ actual =2, predicted=2
    #False positive _ actual=2, predicted=1
    #False negative _ actual=1, predicted=2
    #True negative _ actual=1, predicted=1
    tp=sum((actual_y == 2) & (predicted_y == 2))
    tn=sum((actual_y == 1) & (predicted_y == 1))
    fn=sum((actual_y == 1) & (predicted_y == 2))
    fp=sum((actual_y == 2) & (predicted_y == 1))
    return tp, tn, fp, fn

#calculate accuracy
def compute_accuracy(tp,tn,fn,fp):
    #Acurracy=TP+TN/FP+FN+TP+TN
    return((tp+tn*100)/float(tp+tn+fn+fp) if (tp+tn+fn+fp) != 0 else 0)

#calculate precission
def compute_precision(tp,fp):
    #Acurracy=TP/FP+TP
      return((tp*100)/float(tp+fp) if (tp+fp) != 0 else 0)
    
#calculate recall
def compute_recall(tp,fn):
     #recall=TP/FN+TP
        return ((tp*100)/float(tp+fn) if (tp+fn) != 0 else 0)
    
#calculate f1_score
def compute_f1_score(actual_y, predicted_y):
        tp,tn,fp,fn= compute_tp_tn_fn_fp(actual_y, predicted_y)
        precision=compute_precision(tp,fp)/100 
        recall=compute_recall(tp,fn)/100
        f1_score=(2*precision*recall)/(precision+recall) if (precision+recall) != 0 else 0
        return f1_score

def performance_of_the_model(actual_y,predicted_y): 
    
    tp_r,tn_r, fp_r,fn_r=compute_tp_tn_fn_fp(actual_y,predicted_y)
    print('TP for dt is:',tp_r)
    print('TN for dt is:',tn_r)
    print('FP for dt is:',fp_r)
    print('FN for dt is:',fn_r)
    accuracy=compute_accuracy(tp_r,tn_r,fn_r,fp_r)
    print('accuracy:', accuracy)
    precision=compute_precision(tp_r,fp_r)
    print('precision:', precision)
    recall=compute_recall(tp_r,fn_r)
    print('recall:', recall)
    f1_score=compute_f1_score(actual_y,predicted_y)
    print('f1_score:', f1_score)
    return
    

In [7]:
#Decision Tree Classifier
#Function to perform training with Entropy
dt=DecisionTreeClassifier(criterion="entropy", random_state=0, max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [8]:
# Function to make prediction
y_pred_en=dt.predict(X_test)
#checking performance of the model
print(confusion_matrix(y_test, y_pred_en))
print(classification_report(y_test, y_pred_en))
performance_of_the_model(y_test, y_pred_en)  


[[130  12]
 [ 21  50]]
              precision    recall  f1-score   support

         1.0       0.86      0.92      0.89       142
         2.0       0.81      0.70      0.75        71

    accuracy                           0.85       213
   macro avg       0.83      0.81      0.82       213
weighted avg       0.84      0.85      0.84       213

TP for dt is: 50
TN for dt is: 130
FP for dt is: 21
FN for dt is: 12
accuracy: 61.267605633802816
precision: 70.4225352112676
recall: 80.64516129032258
f1_score: 0.7518796992481203


In [9]:
#Random Forest Classifier
rfc=RandomForestClassifier(max_depth=2, random_state=0)
rfc.fit(X_train, y_train)
predictionRF=rfc.predict(X_test)
#checking performance of the model
print(confusion_matrix(y_test, predictionRF))
print(classification_report(y_test, predictionRF))
performance_of_the_model(y_test, predictionRF) 

[[139   3]
 [ 23  48]]
              precision    recall  f1-score   support

         1.0       0.86      0.98      0.91       142
         2.0       0.94      0.68      0.79        71

    accuracy                           0.88       213
   macro avg       0.90      0.83      0.85       213
weighted avg       0.89      0.88      0.87       213

TP for dt is: 48
TN for dt is: 139
FP for dt is: 23
FN for dt is: 3
accuracy: 65.48356807511738
precision: 67.6056338028169
recall: 94.11764705882354
f1_score: 0.7868852459016393


C:\Users\SARA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [10]:
#define K
import math
math.sqrt(len(y_test))

14.594519519326424

In [11]:
#K-NN classifier
knn=KNeighborsClassifier(n_neighbors=13, p=2, metric='euclidean')

#predict the test set results
knn.fit(X_train, y_train)
predictionKNN=knn.predict(X_test)
#Evaluate model
print(confusion_matrix(y_test, predictionKNN))
print(classification_report(y_test, predictionKNN))
performance_of_the_model(y_test, predictionKNN)

[[137   5]
 [ 19  52]]
              precision    recall  f1-score   support

         1.0       0.88      0.96      0.92       142
         2.0       0.91      0.73      0.81        71

    accuracy                           0.89       213
   macro avg       0.90      0.85      0.87       213
weighted avg       0.89      0.89      0.88       213

TP for dt is: 52
TN for dt is: 137
FP for dt is: 19
FN for dt is: 5
accuracy: 64.56338028169014
precision: 73.2394366197183
recall: 91.2280701754386
f1_score: 0.8124999999999999


In [12]:
# svm Classifier
clf=svm.SVC(kernel="linear", C=0.8,probability=True)
clf.fit(X_train,y_train)
predictionSVM=clf.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionSVM))
print(classification_report(y_test, predictionSVM))
performance_of_the_model(y_test, predictionSVM)

[[135   7]
 [ 17  54]]
              precision    recall  f1-score   support

         1.0       0.89      0.95      0.92       142
         2.0       0.89      0.76      0.82        71

    accuracy                           0.89       213
   macro avg       0.89      0.86      0.87       213
weighted avg       0.89      0.89      0.88       213

TP for dt is: 54
TN for dt is: 135
FP for dt is: 17
FN for dt is: 7
accuracy: 63.63380281690141
precision: 76.05633802816901
recall: 88.52459016393442
f1_score: 0.8181818181818182


In [13]:
#Bagging Classifier
bg=BaggingClassifier(DecisionTreeClassifier(), max_samples=0.5, max_features=1.0, n_estimators=10)
bg=BaggingClassifier()
bg.fit(X_train,y_train)
predictionbg=bg.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionbg))
print(classification_report(y_test, predictionbg))
performance_of_the_model(y_test, predictionbg)

[[136   6]
 [ 18  53]]
              precision    recall  f1-score   support

         1.0       0.88      0.96      0.92       142
         2.0       0.90      0.75      0.82        71

    accuracy                           0.89       213
   macro avg       0.89      0.85      0.87       213
weighted avg       0.89      0.89      0.88       213

TP for dt is: 53
TN for dt is: 136
FP for dt is: 18
FN for dt is: 6
accuracy: 64.09859154929578
precision: 74.64788732394366
recall: 89.83050847457628
f1_score: 0.8153846153846154


In [14]:
#Boosting Classifier- Ada Boost
adb=AdaBoostClassifier(DecisionTreeClassifier(), n_estimators=10, learning_rate=1)
adb.fit(X_train,y_train)
predictionadb=adb.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionadb))
print(classification_report(y_test, predictionadb))
performance_of_the_model(y_test, predictionadb)

[[120  22]
 [ 13  58]]
              precision    recall  f1-score   support

         1.0       0.90      0.85      0.87       142
         2.0       0.72      0.82      0.77        71

    accuracy                           0.84       213
   macro avg       0.81      0.83      0.82       213
weighted avg       0.84      0.84      0.84       213

TP for dt is: 58
TN for dt is: 120
FP for dt is: 13
FN for dt is: 22
accuracy: 56.610328638497656
precision: 81.69014084507042
recall: 72.5
f1_score: 0.7682119205298013


In [15]:
#Naive bayse Classifier
nb=GaussianNB()
nb.fit(X_train,y_train)
predictionnb=nb.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionnb))
print(classification_report(y_test, predictionnb))
performance_of_the_model(y_test, predictionnb)

[[127  15]
 [ 16  55]]
              precision    recall  f1-score   support

         1.0       0.89      0.89      0.89       142
         2.0       0.79      0.77      0.78        71

    accuracy                           0.85       213
   macro avg       0.84      0.83      0.84       213
weighted avg       0.85      0.85      0.85       213

TP for dt is: 55
TN for dt is: 127
FP for dt is: 16
FN for dt is: 15
accuracy: 59.882629107981224
precision: 77.46478873239437
recall: 78.57142857142857
f1_score: 0.7801418439716311


In [38]:
#creat Multilayer neural network Classifier
nn=MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
nn.fit(X_train,y_train)
predictionNN=nn.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionNN))
print(classification_report(y_test, predictionNN))
performance_of_the_model(y_test, predictionNN)



[[118  24]
 [ 14  57]]
              precision    recall  f1-score   support

         1.0       0.89      0.83      0.86       142
         2.0       0.70      0.80      0.75        71

    accuracy                           0.82       213
   macro avg       0.80      0.82      0.81       213
weighted avg       0.83      0.82      0.82       213

TP for dt is: 57
TN for dt is: 118
FP for dt is: 14
FN for dt is: 24
accuracy: 55.666666666666664
precision: 80.28169014084507
recall: 70.37037037037037
f1_score: 0.75


In [17]:
#Voting Classifier- Multiple Model Ensemble
evc=VotingClassifier(estimators=[('dt',dt),('rfc',rfc),('clf',clf),('knn',knn),('bg',bg),('adb',adb),('nb',nb),('nn',nn)], voting='soft')
evc.fit(X_train,y_train)
predictionevc=evc.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionevc))
print(classification_report(y_test, predictionevc))
performance_of_the_model(y_test, predictionevc)

[[136   6]
 [ 18  53]]
              precision    recall  f1-score   support

         1.0       0.88      0.96      0.92       142
         2.0       0.90      0.75      0.82        71

    accuracy                           0.89       213
   macro avg       0.89      0.85      0.87       213
weighted avg       0.89      0.89      0.88       213

TP for dt is: 53
TN for dt is: 136
FP for dt is: 18
FN for dt is: 6
accuracy: 64.09859154929578
precision: 74.64788732394366
recall: 89.83050847457628
f1_score: 0.8153846153846154


In [18]:

#defining learning classifiers
names=["Decision_Tree", "Random_Forest", "linear_SVM","Nearest_Neighbors","Bagging","AdaBoost","Naive_Bayes","Neural_Net","Vothing_classifier"]
classifiers = [dt,rfc,clf,knn,bg,adb,nb,nn,evc]

#Build Model, Apply Model on Test Data & Record Accuracy Scores
scores = []
Fmeasure=[]
for name, clf in zip(names, classifiers):
    clf.fit(X_train, y_train)
    prediction=clf.predict(X_test)
    scores.append(compute_tp_tn_fn_fp(y_test, prediction))
    f1_score=compute_f1_score(y_test,prediction)
    Fmeasure.append(f1_score)
    


In [19]:
scores



[(50, 130, 21, 12),
 (48, 139, 23, 3),
 (54, 135, 17, 7),
 (52, 137, 19, 5),
 (53, 134, 18, 8),
 (57, 117, 14, 25),
 (55, 127, 16, 15),
 (53, 125, 18, 17),
 (53, 135, 18, 7)]

In [20]:
tp=[i[0] for i in scores]


In [21]:
tp

[50, 48, 54, 52, 53, 57, 55, 53, 53]

In [22]:
fp=[i[2] for i in scores]

In [23]:
fp

[21, 23, 17, 19, 18, 14, 16, 18, 18]

In [24]:
Fmeasure

[0.7518796992481203,
 0.7868852459016393,
 0.8181818181818182,
 0.8124999999999999,
 0.803030303030303,
 0.7450980392156864,
 0.7801418439716311,
 0.75177304964539,
 0.8091603053435115]

In [29]:

#define Prediction probabilities
r_probs_ = [0 for _ in range(len(y_test))]
dt_probs = dt.predict_proba(X_test)
rfc_probs = rfc.predict_proba(X_test)
clf_probs = clf.predict_proba(X_test)
knn_probs = knn.predict_proba(X_test)
bg_probs = bg.predict_proba(X_test)
adb_probs = adb.predict_proba(X_test)
nb_probs = nb.predict_proba(X_test)
nn_probs = nn.predict_proba(X_test)
evc_probs = evc.predict_proba(X_test)

#Probabilities for the positive outcome is kept
dt_probs_ = dt_probs[:,1]
rfc_probs_ = rfc_probs[:,1]
clf_probs_ = clf_probs[:,1]
knn_probs_ = knn_probs[:,1]
bg_probs_ = bg_probs[:,1]
adb_probs_ = adb_probs[:,1]
nb_probs_ = nb_probs[:,1]
nn_probs_ = nn_probs[:,1]
evc_probs_ = evc_probs[:,1]
#ROC is the receiver operating characteristic AUROC is the area under the ROC curve
result=[]
r_auc = roc_auc_score(y_test, r_probs_)
dt_auc = roc_auc_score(y_test, dt_probs_)
result.append(dt_auc)
rfc_auc = roc_auc_score(y_test, rfc_probs_)
result.append(rfc_auc)
clf_auc = roc_auc_score(y_test, clf_probs_)
result.append(clf_auc)
knn_auc = roc_auc_score(y_test, knn_probs_)
result.append(knn_auc)
bg_auc = roc_auc_score(y_test, bg_probs_)
result.append(bg_auc)
adb_auc = roc_auc_score(y_test, adb_probs_)
result.append(adb_auc)
nb_auc = roc_auc_score(y_test, nb_probs_)
result.append(nb_auc)
nn_auc = roc_auc_score(y_test, nn_probs_)
result.append(nn_auc)
evc_auc = roc_auc_score(y_test, evc_probs_)
result.append(evc_auc)

#Print AUROC scores
print('Random (chance) Prediction: AUROC = %.3f' % (r_auc))
print('Decision_Tree: AUROC = %.3f' % (dt_auc))
print('Random_Forest: AUROC = %.3f' % (rfc_auc))
print('linear_SVM: AUROC = %.3f' % (clf_auc))
print('Nearest_Neighbors: AUROC = %.3f' % (knn_auc))
print('Bagging: AUROC = %.3f' % (bg_auc))
print('AdaBoost: AUROC = %.3f' % (adb_auc))
print('Naive Bayes: AUROC = %.3f' % (nb_auc))
print('Neural_Net: AUROC = %.3f' % (nn_auc))
print('Vothing_classifier: AUROC = %.3f' % (evc_auc))

#Calculate ROC curve
r_fpr, r_tpr, threshold = roc_curve(y_test, r_probs_,pos_label=1,drop_intermediate=True)
dt_fpr, dt_tpr, threshold = roc_curve(y_test, dt_probs_,pos_label=1,drop_intermediate=True)
rfc_fpr, rfc_tpr, threshold = roc_curve(y_test, rfc_probs_,pos_label=1,drop_intermediate=True)
clf_fpr, clf_tpr, threshold= roc_curve(y_test, clf_probs_,pos_label=1,drop_intermediate=True)
knn_fpr, knn_tpr,threshold = roc_curve(y_test, knn_probs_,pos_label=1,drop_intermediate=True)
bg_fpr, bg_tpr, threshold= roc_curve(y_test, bg_probs_,pos_label=1,drop_intermediate=True)
adb_fpr, adb_tpr, threshold = roc_curve(y_test, adb_probs_,pos_label=1,drop_intermediate=True)
nb_fpr, nb_tpr, threshold = roc_curve(y_test, nb_probs_,pos_label=1,drop_intermediate=True)
nn_fpr, nb_tpr, threshold = roc_curve(y_test, nn_probs_,pos_label=1,drop_intermediate=True)
evc_fpr, evc_tpr, threshold= roc_curve(y_test, evc_probs_,pos_label=1,drop_intermediate=True)


# #Plot the ROC curve
# plt.plot(r_fpr, r_tpr, linestyle='--', label='Random prediction (AUROC = %0.3f)' % r_auc)
# plt.plot(dt_fpr, dt_tpr, marker='.', label='Random Forest (AUROC = %0.3f)' % dt_auc)
# plt.plot(rfc_fpr, rfc_tpr, marker='.', label='Naive Bayes (AUROC = %0.3f)' % rfc_auc)
# plt.plot(clf_fpr, clf_tpr, marker='.', label='linear_SVM (AUROC = %0.3f)' % clf_auc)
# plt.plot(knn_fpr, knn_tpr, marker='.', label='Nearest_Neighbors(AUROC = %0.3f)' % knn_auc)
# plt.plot(bg_fpr, bg_tpr, marker='.', label='Bagging (AUROC = %0.3f)' % bg_auc)
# plt.plot(adb_fpr, adb_tpr, marker='.', label='AdaBoost (AUROC = %0.3f)' % adb_auc)
# plt.plot(nb_fpr, nb_tpr, marker='.', label='Naive_Bayes (AUROC = %0.3f)' % nb_auc)
# plt.plot(nn_fpr, nn_tpr, marker='.', label='Neural_Net (AUROC = %0.3f)' % nn_auc)
# plt.plot(evc_fpr, evc_tpr, marker='.', label='Vothing_classifier (AUROC = %0.3f)' % evc_auc)
# # Title
# plt.title('ROC Plot')
# plt.legend(loc = 'lower right')
# plt.plot([0, 1], [0, 1],'r--')
# plt.xlim([0, 1])
# plt.ylim([0, 1])
# plt.ylabel('True Positive Rate')
# plt.xlabel('False Positive Rate')
# plt.show()

Random (chance) Prediction: AUROC = 0.500
Decision_Tree: AUROC = 0.829
Random_Forest: AUROC = 0.895
linear_SVM: AUROC = 0.896
Nearest_Neighbors: AUROC = 0.907
Bagging: AUROC = 0.908
AdaBoost: AUROC = 0.813
Naive Bayes: AUROC = 0.854
Neural_Net: AUROC = 0.824
Vothing_classifier: AUROC = 0.896


In [30]:
result

[0.8288038087681016,
 0.8951596905375917,
 0.8964491172386432,
 0.9068141241817099,
 0.9080539575481055,
 0.8133802816901409,
 0.8537492560999802,
 0.824489188653045,
 0.8964491172386432]

In [36]:
#create data frame of model performance
df = pd.DataFrame()
df['Machine Learning algorithms'] = names
df['F-measure-Twitter'] = Fmeasure 
df['TP-Twitter']=tp
df['FP-Twitter']=fp
df['AUC-Twitter']=result

In [37]:
#adding colors to the data frame
cm = sns.light_palette("#CC8899", as_cmap=True)
s = df.style.background_gradient(cmap=cm)
s