In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets.samples_generator import make_blobs
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report, f1_score, precision_recall_curve
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import roc_curve, roc_auc_score,auc
from sklearn.feature_selection import VarianceThreshold
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectFromModel
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import label_binarize



In [3]:
fullFileName='youtube.csv'
data=pd.read_csv(fullFileName, sep=' ')

data_=data.replace(['1:','2:','3:','4:','5:','6:','7:','8:','9:','10:','11:','12:','13:','14:','15:','16:','17:','18:','19:',
                   '20:','21:','22:','23:','24:','25:','25:','27:','28:','29:','30:','31:','32:','33:','34:','35:','36:','37:','38:','39:','40:','50:','60:'],'',regex=True).astype(float) 

data_.columns = ['user_class','Total number of views of all videos uploaded','Total number of views of all video responses',
                 'Total number of views of all responded videos',
'Total duration of all videos uploaded','Total duration of all video responses','Total duration of all responded videos',
'Total number of ratings of all videos uploaded','Total number of ratings of all video responses','Total number of ratings of all responded videos',
'Total number of comments of all videos uploaded','Total number of comments of all video responses','Total number of comments of all responded videos','Total number of times that all videos uploaded were added as favorite',
'Total number of times that all video responses were added as favorite','Total number of times that all responded videos were added as favorite','Total number of honors of all videos uploaded','Total number of honors of all video responses',
'Total number of honors of all responded videos','Total number of links of all videos uploaded','Total number of links of all video responses','Total number of links of all responded videos',
'Average number of views of all videos uploaded','Average number of views of all video responses','Average number of views of all responded videos',
 'Average duration of all videos uploaded','Average duration of all video responses','Average duration of all responded videos','Average number of ratings of all videos uploaded','Average number of ratings of all video responses',
'Average number of ratings of all responded videos','Average number of comments of all videos uploaded','Average number of comments of all video responses','Average number of comments of all responded videos','Average number of times that all videos uploaded were added as favorite',
'Average number of times that all video responses were added as favorite','Average number of times that all responded videos were added as favorite','Average number of honors of all videos uploaded','Average number of honors of all video responses','Average number of honors of all responded videos',
'Average number of links of all videos uploaded','Average number of links of all video responses','Average number of links of all responded videos','Clustering Coefficient','Reciprocity','UserRank','Betweenness','Assortativity in-in degree',
'Assortativity in-out degree','Assortativity out-in degree','Assortativity out-out degree','Number of responses posted','Number of responses received','Number of friends','Number of videos watched','Number of videos uploaded',
'Number of videos added as favorite','Number of subscriptions','Number of subscribers','Maximum number of videos uploaded in 24 hours','Average time between video uploads']              

data_['user_class'].replace((1), (3), inplace = True)
data_['user_class'].value_counts()


3.0    672
2.0    156
Name: user_class, dtype: int64

In [4]:
#first we count the number of missing values in each row in pandas dataframe
data_.isnull().sum(axis=0)
print("Dataset Lenght:: ",len(data_))
print("Dataset shape:: ", data_.shape)

Dataset Lenght::  828
Dataset shape::  (828, 61)


In [5]:
print("Dataset:: ")
data_.head()
data_.info()
data_.describe()

Dataset:: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828 entries, 0 to 827
Data columns (total 61 columns):
user_class                                                                  828 non-null float64
Total number of views of all videos uploaded                                828 non-null float64
Total number of views of all video responses                                828 non-null float64
Total number of views of all responded videos                               828 non-null float64
Total duration of all videos uploaded                                       828 non-null float64
Total duration of all video responses                                       828 non-null float64
Total duration of all responded videos                                      828 non-null float64
Total number of ratings of all videos uploaded                              828 non-null float64
Total number of ratings of all video responses                              828 non-null float64
Total numbe

user_class  Total number of views of all videos uploaded  \
count  828.000000                                  8.280000e+02   
mean     2.811594                                  4.132443e+05   
std      0.391272                                  1.488269e+06   
min      2.000000                                  9.000000e+00   
25%      3.000000                                  8.856750e+03   
50%      3.000000                                  4.818800e+04   
75%      3.000000                                  2.449685e+05   
max      3.000000                                  1.952458e+07   

       Total number of views of all video responses  \
count                                  8.280000e+02   
mean                                   9.065943e+04   
std                                    3.501392e+05   
min                                    9.000000e+00   
25%                                    1.745750e+03   
50%                                    1.111550e+04   
75%                                    4.635350e+04   
max                                    6.454217e+06   

       Total number of views of all responded videos  \
count                                   8.280000e+02   
mean                                    8.664683e+06   
std                                     1.764183e+07   
min                                     3.110000e+02   
25%                                     1.344152e+05   
50%                                     1.039888e+06   
75%                                     7.824169e+06   
max                                     1.745945e+08   

       Total duration of all videos uploaded  \
count                             828.000000   
mean                            12916.522947   
std                             26038.343497   
min                                 0.000000   
25%                              1821.250000   
50%                              5353.500000   
75%                             13791.250000   
max                            399444.000000   

       Total duration of all video responses  \
count                             828.000000   
mean                             2786.105072   
std                              5167.388046   
min                                 0.000000   
25%                               320.250000   
50%                               996.500000   
75%                              3076.500000   
max                             59257.000000   

       Total duration of all responded videos  \
count                              828.000000   
mean                              2846.300725   
std                               5202.768288   
min                                  8.000000   
25%                                377.000000   
50%                               1063.000000   
75%                               3000.750000   
max                              64994.000000   

       Total number of ratings of all videos uploaded  \
count                                      828.000000   
mean                                      2523.701691   
std                                      10580.569270   
min                                          0.000000   
25%                                         61.750000   
50%                                        327.500000   
75%                                       1524.750000   
max                                     154072.000000   

       Total number of ratings of all video responses  \
count                                      828.000000   
mean                                       643.015700   
std                                       2989.969344   
min                                          0.000000   
25%                                         15.000000   
50%                                         86.500000   
75%                                        356.250000   
max                                      67990.000000   

       Total number of ratings of all responded videos  ...  \
cou

In [6]:
array=data_.values
X1 = array[:,1: ]
Y = array[:,0]


""" MIN MAX SCALER """
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
# Scaled feature 
X2 = min_max_scaler.fit_transform(X1) 
  
""" Standardisation """ 
Standardisation = preprocessing.StandardScaler() 
# Scaled feature 
X = Standardisation.fit_transform(X2) 

#Spliting Dataset into Test and Train
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=0.2, random_state=0)


X1.shape,Y.shape

((828, 60), (828,))

In [7]:
#calculate TP, TN,FN,FP
def compute_tp_tn_fn_fp(actual_y, predicted_y):
    #we define spam class(2) as positive rate, and not spam class(3) as negative rate
    #True positive _ actual =2, predicted=2
    #False positive _ actual=2, predicted=3
    #False negative _ actual=3, predicted=2
    #True negative _ actual=3, predicted=3
    tp=sum((actual_y == 2) & (predicted_y == 2))
    tn=sum((actual_y == 3) & (predicted_y == 3))
    fn=sum((actual_y == 3) & (predicted_y == 2))
    fp=sum((actual_y == 2) & (predicted_y == 3))
    return tp, tn, fp, fn

#calculate accuracy
def compute_accuracy(tp,tn,fn,fp):
    #Acurracy=TP+TN/FP+FN+TP+TN
    return((tp+tn*100)/float(tp+tn+fn+fp) if (tp+tn+fn+fp) != 0 else 0)

#calculate precission
def compute_precision(tp,fp):
    #Acurracy=TP/FP+TP
      return((tp*100)/float(tp+fp) if (tp+fp) != 0 else 0)
    
#calculate recall
def compute_recall(tp,fn):
     #recall=TP/FN+TP
        return ((tp*100)/float(tp+fn) if (tp+fn) != 0 else 0)
    
#calculate f1_score
def compute_f1_score(actual_y, predicted_y):
        tp,tn,fp,fn= compute_tp_tn_fn_fp(actual_y, predicted_y)
        precision=compute_precision(tp,fp)/100 
        recall=compute_recall(tp,fn)/100
        f1_score=(2*precision*recall)/(precision+recall) if (precision+recall) != 0 else 0
        return f1_score

def performance_of_the_model(actual_y,predicted_y): 
    
    tp_r,tn_r, fp_r,fn_r=compute_tp_tn_fn_fp(actual_y,predicted_y)
    print('TP for dt is:',tp_r)
    print('TN for dt is:',tn_r)
    print('FP for dt is:',fp_r)
    print('FN for dt is:',fn_r)
    accuracy=compute_accuracy(tp_r,tn_r,fn_r,fp_r)
    print('accuracy:', accuracy)
    precision=compute_precision(tp_r,fp_r)
    print('precision:', precision)
    recall=compute_recall(tp_r,fn_r)
    print('recall:', recall)
    f1_score=compute_f1_score(actual_y,predicted_y)
    print('f1_score:', f1_score)
    return
    

In [8]:
#Decision Tree Classifier
#Function to perform training with Entropy
dt=DecisionTreeClassifier(criterion="entropy", random_state=0, max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [9]:
# Function to make prediction
y_pred_en=dt.predict(X_test)
#checking performance of the model
print(confusion_matrix(y_test, y_pred_en))
print(classification_report(y_test, y_pred_en))
performance_of_the_model(y_test, y_pred_en)  


[[ 10  11]
 [  5 140]]
              precision    recall  f1-score   support

         2.0       0.67      0.48      0.56        21
         3.0       0.93      0.97      0.95       145

    accuracy                           0.90       166
   macro avg       0.80      0.72      0.75       166
weighted avg       0.89      0.90      0.90       166

TP for dt is: 10
TN for dt is: 140
FP for dt is: 11
FN for dt is: 5
accuracy: 84.39759036144578
precision: 47.61904761904762
recall: 66.66666666666667
f1_score: 0.5555555555555556


In [10]:
#Random Forest Classifier
rfc=RandomForestClassifier(max_depth=2, random_state=0)
rfc.fit(X_train, y_train)
predictionRF=rfc.predict(X_test)
#checking performance of the model
print(confusion_matrix(y_test, predictionRF))
print(classification_report(y_test, predictionRF))
performance_of_the_model(y_test, predictionRF) 

[[ 11  10]
 [  5 140]]
              precision    recall  f1-score   support

         2.0       0.69      0.52      0.59        21
         3.0       0.93      0.97      0.95       145

    accuracy                           0.91       166
   macro avg       0.81      0.74      0.77       166
weighted avg       0.90      0.91      0.90       166

TP for dt is: 11
TN for dt is: 140
FP for dt is: 10
FN for dt is: 5
accuracy: 84.40361445783132
precision: 52.38095238095238
recall: 68.75
f1_score: 0.5945945945945946


C:\Users\SARA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [11]:
#define K
import math
math.sqrt(len(y_test))

12.884098726725126

In [12]:
#K-NN classifier
knn=KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')

#predict the test set results
knn.fit(X_train, y_train)
predictionKNN=knn.predict(X_test)
#Evaluate model
print(confusion_matrix(y_test, predictionKNN))
print(classification_report(y_test, predictionKNN))
performance_of_the_model(y_test, predictionKNN)

[[ 10  11]
 [  5 140]]
              precision    recall  f1-score   support

         2.0       0.67      0.48      0.56        21
         3.0       0.93      0.97      0.95       145

    accuracy                           0.90       166
   macro avg       0.80      0.72      0.75       166
weighted avg       0.89      0.90      0.90       166

TP for dt is: 10
TN for dt is: 140
FP for dt is: 11
FN for dt is: 5
accuracy: 84.39759036144578
precision: 47.61904761904762
recall: 66.66666666666667
f1_score: 0.5555555555555556


In [13]:
# svm Classifier
clf=svm.SVC(kernel="linear", C=0.8,probability=True)
clf.fit(X_train,y_train)
predictionSVM=clf.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionSVM))
print(classification_report(y_test, predictionSVM))
performance_of_the_model(y_test, predictionSVM)

[[ 11  10]
 [  7 138]]
              precision    recall  f1-score   support

         2.0       0.61      0.52      0.56        21
         3.0       0.93      0.95      0.94       145

    accuracy                           0.90       166
   macro avg       0.77      0.74      0.75       166
weighted avg       0.89      0.90      0.89       166

TP for dt is: 11
TN for dt is: 138
FP for dt is: 10
FN for dt is: 7
accuracy: 83.1987951807229
precision: 52.38095238095238
recall: 61.111111111111114
f1_score: 0.5641025641025642


In [14]:
#Bagging Classifier
bg=BaggingClassifier(DecisionTreeClassifier(), max_samples=0.5, max_features=1.0, n_estimators=10)
bg=BaggingClassifier()
bg.fit(X_train,y_train)
predictionbg=bg.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionbg))
print(classification_report(y_test, predictionbg))
performance_of_the_model(y_test, predictionbg)

[[ 13   8]
 [ 10 135]]
              precision    recall  f1-score   support

         2.0       0.57      0.62      0.59        21
         3.0       0.94      0.93      0.94       145

    accuracy                           0.89       166
   macro avg       0.75      0.78      0.76       166
weighted avg       0.90      0.89      0.89       166

TP for dt is: 13
TN for dt is: 135
FP for dt is: 8
FN for dt is: 10
accuracy: 81.40361445783132
precision: 61.904761904761905
recall: 56.52173913043478
f1_score: 0.5909090909090909


In [15]:
#Boosting Classifier- Ada Boost
adb=AdaBoostClassifier(DecisionTreeClassifier(), n_estimators=10, learning_rate=1)
adb.fit(X_train,y_train)
predictionadb=adb.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionadb))
print(classification_report(y_test, predictionadb))
performance_of_the_model(y_test, predictionadb)

[[ 13   8]
 [ 12 133]]
              precision    recall  f1-score   support

         2.0       0.52      0.62      0.57        21
         3.0       0.94      0.92      0.93       145

    accuracy                           0.88       166
   macro avg       0.73      0.77      0.75       166
weighted avg       0.89      0.88      0.88       166

TP for dt is: 13
TN for dt is: 133
FP for dt is: 8
FN for dt is: 12
accuracy: 80.1987951807229
precision: 61.904761904761905
recall: 52.0
f1_score: 0.5652173913043478


In [16]:
#Naive bayse Classifier
nb=GaussianNB()
nb.fit(X_train,y_train)
predictionnb=nb.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionnb))
print(classification_report(y_test, predictionnb))
performance_of_the_model(y_test, predictionnb)

[[20  1]
 [98 47]]
              precision    recall  f1-score   support

         2.0       0.17      0.95      0.29        21
         3.0       0.98      0.32      0.49       145

    accuracy                           0.40       166
   macro avg       0.57      0.64      0.39       166
weighted avg       0.88      0.40      0.46       166

TP for dt is: 20
TN for dt is: 47
FP for dt is: 1
FN for dt is: 98
accuracy: 28.433734939759034
precision: 95.23809523809524
recall: 16.949152542372882
f1_score: 0.28776978417266186


In [17]:
#creat Multilayer neural network Classifier
nn=MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
nn.fit(X_train,y_train)
predictionNN=nn.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionNN))
print(classification_report(y_test, predictionNN))
performance_of_the_model(y_test, predictionNN)



[[ 16   5]
 [ 20 125]]
              precision    recall  f1-score   support

         2.0       0.44      0.76      0.56        21
         3.0       0.96      0.86      0.91       145

    accuracy                           0.85       166
   macro avg       0.70      0.81      0.74       166
weighted avg       0.90      0.85      0.87       166

TP for dt is: 16
TN for dt is: 125
FP for dt is: 5
FN for dt is: 20
accuracy: 75.39759036144578
precision: 76.19047619047619
recall: 44.44444444444444
f1_score: 0.5614035087719298


In [18]:
#Voting Classifier- Multiple Model Ensemble
evc=VotingClassifier(estimators=[('dt',dt),('rfc',rfc),('clf',clf),('knn',knn),('bg',bg),('adb',adb),('nb',nb),('nn',nn)], voting='soft')
evc.fit(X_train,y_train)
predictionevc=evc.predict(X_test)

#Evaluate model
print(confusion_matrix(y_test, predictionevc))
print(classification_report(y_test, predictionevc))
performance_of_the_model(y_test, predictionevc)

[[ 14   7]
 [  8 137]]
              precision    recall  f1-score   support

         2.0       0.64      0.67      0.65        21
         3.0       0.95      0.94      0.95       145

    accuracy                           0.91       166
   macro avg       0.79      0.81      0.80       166
weighted avg       0.91      0.91      0.91       166

TP for dt is: 14
TN for dt is: 137
FP for dt is: 7
FN for dt is: 8
accuracy: 82.6144578313253
precision: 66.66666666666667
recall: 63.63636363636363
f1_score: 0.6511627906976745


In [19]:

#defining learning classifiers
names=["Decision_Tree", "Random_Forest", "linear_SVM","Nearest_Neighbors","Bagging","AdaBoost","Naive_Bayes","Neural_Net","Vothing_classifier"]
classifiers = [dt,rfc,clf,knn,bg,adb,nb,nn,evc]

#Build Model, Apply Model on Test Data & Record Accuracy Scores
scores = []
Fmeasure=[]
for name, clf in zip(names, classifiers):
    clf.fit(X_train, y_train)
    prediction=clf.predict(X_test)
    scores.append(compute_tp_tn_fn_fp(y_test, prediction))
    f1_score=compute_f1_score(y_test,prediction)
    Fmeasure.append(f1_score)
    


In [20]:
scores



[(10, 140, 11, 5),
 (11, 140, 10, 5),
 (11, 138, 10, 7),
 (10, 140, 11, 5),
 (13, 138, 8, 7),
 (12, 133, 9, 12),
 (20, 47, 1, 98),
 (16, 125, 5, 20),
 (14, 138, 7, 7)]

In [21]:
tp=[i[0] for i in scores]


In [22]:
tp

[10, 11, 11, 10, 13, 12, 20, 16, 14]

In [23]:
fp=[i[2] for i in scores]

In [24]:
fp

[11, 10, 10, 11, 8, 9, 1, 5, 7]

In [25]:
Fmeasure

[0.5555555555555556,
 0.5945945945945946,
 0.5641025641025642,
 0.5555555555555556,
 0.6341463414634146,
 0.5333333333333333,
 0.28776978417266186,
 0.5614035087719298,
 0.6666666666666667]

In [27]:
r_probs_ = [0 for _ in range(len(y_test))]
dt_probs = dt.predict_proba(X_test)
rfc_probs = rfc.predict_proba(X_test)
clf_probs = clf.predict_proba(X_test)
knn_probs = knn.predict_proba(X_test)
bg_probs = bg.predict_proba(X_test)
adb_probs = adb.predict_proba(X_test)
nb_probs = nb.predict_proba(X_test)
nn_probs = nn.predict_proba(X_test)
evc_probs = evc.predict_proba(X_test)

#Probabilities for the positive outcome is kept
dt_probs_ = dt_probs[:,1]
rfc_probs_ = rfc_probs[:,1]
clf_probs_ = clf_probs[:,1]
knn_probs_ = knn_probs[:,1]
bg_probs_ = bg_probs[:,1]
adb_probs_ = adb_probs[:,1]
nb_probs_ = nb_probs[:,1]
nn_probs_ = nn_probs[:,1]
evc_probs_ = evc_probs[:,1]
#ROC is the receiver operating characteristic AUROC is the area under the ROC curve
result=[]
r_auc = roc_auc_score(y_test, r_probs_)
dt_auc = roc_auc_score(y_test, dt_probs_)
result.append(dt_auc)
rfc_auc = roc_auc_score(y_test, rfc_probs_)
result.append(rfc_auc)
clf_auc = roc_auc_score(y_test, clf_probs_)
result.append(clf_auc)
knn_auc = roc_auc_score(y_test, knn_probs_)
result.append(knn_auc)
bg_auc = roc_auc_score(y_test, bg_probs_)
result.append(bg_auc)
adb_auc = roc_auc_score(y_test, adb_probs_)
result.append(adb_auc)
nb_auc = roc_auc_score(y_test, nb_probs_)
result.append(nb_auc)
nn_auc = roc_auc_score(y_test, nn_probs_)
result.append(nn_auc)
evc_auc = roc_auc_score(y_test, evc_probs_)
result.append(evc_auc)

#Print AUROC scores
print('Random (chance) Prediction: AUROC = %.3f' % (r_auc))
print('Decision_Tree: AUROC = %.3f' % (dt_auc))
print('Random_Forest: AUROC = %.3f' % (rfc_auc))
print('linear_SVM: AUROC = %.3f' % (clf_auc))
print('Nearest_Neighbors: AUROC = %.3f' % (knn_auc))
print('Bagging: AUROC = %.3f' % (bg_auc))
print('AdaBoost: AUROC = %.3f' % (adb_auc))
print('Naive Bayes: AUROC = %.3f' % (nb_auc))
print('Neural_Net: AUROC = %.3f' % (nn_auc))
print('Vothing_classifier: AUROC = %.3f' % (evc_auc))

#Calculate ROC curve
r_fpr, r_tpr, threshold = roc_curve(y_test, r_probs_,pos_label=1,drop_intermediate=True)
dt_fpr, dt_tpr, threshold = roc_curve(y_test, dt_probs_,pos_label=1,drop_intermediate=True)
rfc_fpr, rfc_tpr, threshold = roc_curve(y_test, rfc_probs_,pos_label=1,drop_intermediate=True)
clf_fpr, clf_tpr, threshold= roc_curve(y_test, clf_probs_,pos_label=1,drop_intermediate=True)
knn_fpr, knn_tpr,threshold = roc_curve(y_test, knn_probs_,pos_label=1,drop_intermediate=True)
bg_fpr, bg_tpr, threshold= roc_curve(y_test, bg_probs_,pos_label=1,drop_intermediate=True)
adb_fpr, adb_tpr, threshold = roc_curve(y_test, adb_probs_,pos_label=1,drop_intermediate=True)
nb_fpr, nb_tpr, threshold = roc_curve(y_test, nb_probs_,pos_label=1,drop_intermediate=True)
nn_fpr, nb_tpr, threshold = roc_curve(y_test, nn_probs_,pos_label=1,drop_intermediate=True)
evc_fpr, evc_tpr, threshold= roc_curve(y_test, evc_probs_,pos_label=1,drop_intermediate=True)


# #Plot the ROC curve
# plt.plot(r_fpr, r_tpr, linestyle='--', label='Random prediction (AUROC = %0.3f)' % r_auc)
# plt.plot(dt_fpr, dt_tpr, marker='.', label='Random Forest (AUROC = %0.3f)' % dt_auc)
# plt.plot(rfc_fpr, rfc_tpr, marker='.', label='Naive Bayes (AUROC = %0.3f)' % rfc_auc)
# plt.plot(clf_fpr, clf_tpr, marker='.', label='linear_SVM (AUROC = %0.3f)' % clf_auc)
# plt.plot(knn_fpr, knn_tpr, marker='.', label='Nearest_Neighbors(AUROC = %0.3f)' % knn_auc)
# plt.plot(bg_fpr, bg_tpr, marker='.', label='Bagging (AUROC = %0.3f)' % bg_auc)
# plt.plot(adb_fpr, adb_tpr, marker='.', label='AdaBoost (AUROC = %0.3f)' % adb_auc)
# plt.plot(nb_fpr, nb_tpr, marker='.', label='Naive_Bayes (AUROC = %0.3f)' % nb_auc)
# plt.plot(nn_fpr, nn_tpr, marker='.', label='Neural_Net (AUROC = %0.3f)' % nn_auc)
# plt.plot(evc_fpr, evc_tpr, marker='.', label='Vothing_classifier (AUROC = %0.3f)' % evc_auc)
# # Title
# plt.title('ROC Plot')
# plt.legend(loc = 'lower right')
# plt.plot([0, 1], [0, 1],'r--')
# plt.xlim([0, 1])
# plt.ylim([0, 1])
# plt.ylabel('True Positive Rate')
# plt.xlabel('False Positive Rate')
# plt.show()

Random (chance) Prediction: AUROC = 0.500
Decision_Tree: AUROC = 0.828
Random_Forest: AUROC = 0.862
linear_SVM: AUROC = 0.910
Nearest_Neighbors: AUROC = 0.851
Bagging: AUROC = 0.918
AdaBoost: AUROC = 0.744
Naive Bayes: AUROC = 0.853
Neural_Net: AUROC = 0.864
Vothing_classifier: AUROC = 0.910


C:\Users\SARA\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py:659: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)


In [28]:
result

[0.8275862068965517,
 0.861904761904762,
 0.909688013136289,
 0.8507389162561576,
 0.9177339901477833,
 0.744334975369458,
 0.8532019704433498,
 0.864367816091954,
 0.909688013136289]

In [31]:
#create data frame of model performance
df = pd.DataFrame()
df['Machine Learning algorithms'] = names
df['F-measure-YouTube'] = Fmeasure 
df['TP-YouTube']=tp
df['FP-YouTube']=fp
df['AUC-YouTube']=result

In [32]:
#adding colors to the data frame
cm = sns.light_palette("#40E0D0", as_cmap=True)
s = df.style.background_gradient(cmap=cm)
s